language: java
jdk:
  - oraclejdk8

# Build the project
script:
  - ./gradlew build --scan -s

# Store the Gradle cache
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Publish to Github when creating a tag
deploy:
  - provider: releases
    api_key: ${GITHUB_KEY}
    file_glob: true
    file:
      - ./*/**/build/libs/*.jar
    skip_cleanup: true
    on:
      repo: Virtlink/autojar
      branch: master
      tags: true

# Environment variables
env:
  global:
    secure: gCXHvu8q1bOsmAiyGjAGtq/WWDBYITQipXcW8HGKwEUYPzCjykOMTvqdzT84HzDAxQqEz0w7urOkIX+NkhK8lLJpowAOFAYcE4Apt+XO+MqoBkIZWHY53/rQx7B/F6SVB514+KfNyKsVsMLPQQx93KiZJ0HgbZpy+CIq4wsDI1aJr75bqGtzRx8yUd8YEXq9eow2EF7uzBVI7TpOmczy5+kFBO/QeReSRNXCO+DI7r1HAjvYgwk9t7uqk3cgbywaP+VH6v8kno7SbQAuqUJlxEAp2BkxLJbTe/sR5Al78ua5CSuOW3s+PuRhI9u8IdcQh7zk/53MV8MKR3rjPJEsN4xmHuoHeIh777V2bCXg5i6fyQlPf0j6H9/Bfie95RO3xMBBzuWNxovCHc61M3PRKc6IPR2FQL83egjcPB/BFpuxpyoBSCdhwWHLcNuVPRrgHZX2qq6e8q2xGGeVYLKy2PI8p9kYAx4/4DKfhb2ooMIIq6NrjIkUuOaDmx8/lqiC5gwknDZ+gu36NnmpP00B/1fJgyU0E5d9otcIEijVfVd8k9I6N6WtcaWtiwBSa8MvD8FHbIVS5L9CVzeUt9ss/a+QqcXswrVxh0NsGjdfNm9rsE9SHWN82J+yFL11cKftzFF2bLP2bQab4/ORFSmDRuPVcnzr6+bD/vFpO71fyiU=
